const products = [
  {
    id: 1,
    name: 'Nike Air Max 270',
    price: 149.99,
    image: 'https://cdn.pixabay.com/photo/2016/11/19/18/06/feet-1840619_640.jpg',
    category: 'Footwear',
    onSale: true,
    description: 'Nike Air Max 270 provides unrivaled comfort with a bold look.',
    visible: false,
  },
  {
    id: 2,
    name: 'Apple iPhone 13',
    price: 799.99,
    image: 'https://cdn.pixabay.com/photo/2021/09/25/17/43/iphone-13-6655518_640.jpg',
    category: 'Electronics',
    onSale: false,
    description: 'The new Apple iPhone 13 with advanced dual-camera system.',
    visible: true,
  },
  {
    id: 3,
    name: 'Sony WH-1000XM4',
    price: 349.99,
    image: 'https://cdn.pixabay.com/photo/2022/10/06/21/49/headphones-7503631_640.jpg',
    category: 'Accessories',
    onSale: true,
    description: 'Industry-leading noise canceling with Dual Noise Sensor technology.',
    visible: false,
  },
  {
    id: 4,
    name: 'Samsung Galaxy S21',
    price: 699.99,
    image: 'https://cdn.pixabay.com/photo/2019/12/27/01/46/samsung-4721542_640.jpg',
    category: 'Electronics',
    onSale: false,
    description: 'The Samsung Galaxy S21 features a sleek new design and powerful performance.',
    visible: true,
  },
  {
    id: 5,
    name: 'Adidas Ultraboost 21',
    price: 180.00,
    image: 'https://cdn.pixabay.com/photo/2017/07/13/02/53/shoe-2498994_640.jpg',
    category: 'Footwear',
    onSale: true,
    description: 'Responsive running shoes with the comfort of Ultraboost technology.',
    visible: false,
  },
  {
    id: 6,
    name: 'Dell XPS 13',
    price: 999.99,
    image: 'https://cdn.pixabay.com/photo/2015/01/21/14/14/macbook-606763_960_720.jpg',
    category: 'Computers',
    onSale: false,
    description: 'The Dell XPS 13 offers an exceptional 4K display and powerful performance.',
    visible: true,
  },
  {
    id: 7,
    name: 'Bose QuietComfort Earbuds',
    price: 279.00,
    image: 'https://cdn.pixabay.com/photo/2017/08/07/10/21/earphones-2602313_640.jpg',
    category: 'Accessories',
    onSale: true,
    description: 'Bose QuietComfort Earbuds deliver world-class noise cancelling.',
    visible: false,
  },
  {
    id: 8,
    name: 'Amazon Kindle Paperwhite',
    price: 129.99,
    image: 'https://cdn.pixabay.com/photo/2015/05/26/22/37/kindle-785695_640.jpg',
    category: 'Electronics',
    onSale: false,
    description: 'The Kindle Paperwhite features a high-resolution display and waterproof design.',
    visible: true,
  },
  {
    id: 9,
    name: 'Fitbit Charge 4',
    price: 129.95,
    image: 'https://cdn.pixabay.com/photo/2017/07/31/11/39/green-2557523_640.jpg',
    category: 'Accessories',
    onSale: true,
    description: 'The Fitbit Charge 4 offers built-in GPS and heart rate tracking.',
    visible: false,
  },
  {
    id: 10,
    name: 'HP Spectre x360',
    price: 1249.99,
    image: 'https://cdn.pixabay.com/photo/2017/02/25/02/32/b-w-2096808_1280.jpg',
    category: 'Computers',
    onSale: false,
    description: 'The HP Spectre x360 is a powerful 2-in-1 laptop with a stunning display.',
    visible: true,
  },
  {
    id: 11,
    name: 'Canon EOS R5',
    price: 3899.00,
    image: 'https://cdn.pixabay.com/photo/2022/04/04/14/42/camera-7111476_1280.jpg',
    category: 'Cameras',
    onSale: false,
    description: 'The Canon EOS R5 offers high resolution and incredible performance.',
    visible: true,
  },
  {
    id: 12,
    name: 'GoPro HERO9',
    price: 399.99,
    image: 'https://cdn.pixabay.com/photo/2017/08/06/10/42/camera-2591164_640.jpg',
    category: 'Cameras',
    onSale: true,
    description: 'The GoPro HERO9 captures stunning 5K video and 20MP photos.',
    visible: false,
  },
  {
    id: 13,
    name: 'Microsoft Surface Pro 7',
    price: 749.99,
    image: 'https://cdn.pixabay.com/photo/2019/06/15/09/26/laptop-4275110_640.jpg',
    category: 'Computers',
    onSale: false,
    description: 'The Surface Pro 7 offers versatility with a powerful tablet-to-laptop design.',
    visible: true,
  },
  {
    id: 14,
    name: 'JBL Flip 5',
    price: 119.95,
    image: 'https://cdn.pixabay.com/photo/2020/12/03/10/33/speaker-5800162_640.jpg',
    category: 'Accessories',
    onSale: true,
    description: 'JBL Flip 5 delivers bold sound and powerful bass in a portable design.',
    visible: false,
  },
  {
    id: 15,
    name: 'Samsung QLED TV',
    price: 1499.99,
    image: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ6M9wYG9Rk9ngXg2PvhfThnNQjOvUYGa6Vzg&s',
    category: 'Electronics',
    onSale: false,
    description: 'The Samsung QLED TV offers stunning picture quality and smart features.',
    visible: true,
  },
  {
    id: 16,
    name: 'Apple MacBook Pro',
    price: 2399.99,
    image: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSPrVVS7-LVLUhRHjgN5qk7isUdJz18U1MpPQ&s',
    category: 'Computers',
    onSale: false,
    description: 'The Apple MacBook Pro features the powerful M1 chip and a stunning display.',
    visible: true,
  },
  {
    id: 17,
    name: 'Nest Learning Thermostat',
    price: 249.99,
    image: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ6urva2AT7_UWJtVQ7hRfNviPxayYa4bLQ0w&s',
    category: 'Home',
    onSale: true,
    description: 'The Nest Learning Thermostat saves energy and learns your schedule.',
    visible: false,
  },
  {
    id: 18,
    name: 'Dyson V11 Vacuum',
    price: 599.99,
    image: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ2WW7_iTG7mhQrx4a_Rdc9RKlPfrMJZZ5LbA&s',
    category: 'Home',
    onSale: false,
    description: 'The Dyson V11 offers powerful suction and intelligent cleaning modes.',
    visible: true,
  },
  {
    id: 19,
    name: 'Sony PlayStation 5',
    price: 499.99,
    image: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQYs3Lkev3LY62GHxR16vfLFvT32jrQIQ3Luw&s',
    category: 'Gaming',
    onSale: false,
    description: 'The PlayStation 5 offers immersive gaming with stunning graphics and performance.',
    visible: true,
  },
  {
    id: 20,
    name: 'Oculus Quest 2',
    price: 299.00,
    image: 'https://assets.newatlas.com/dims4/default/d3da2bd/2147483647/strip/true/crop/3443x2295+573+320/resize/1200x800!/quality/90/?url=http%3A%2F%2Fnewatlas-brightspot.s3.amazonaws.com%2F3a%2F0a%2F70c848b546efa2fdc138f271c99f%2Flifestyle-1.jpg',
    category: 'Gaming',
    onSale: true,
    description: 'The Oculus Quest 2 offers an all-in-one VR experience with no PC required.',
    visible: false,
  },
];

export default products;
